version: "3"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - database-volume:/var/lib/postgresql/data
  node:
    build: ./
    stop_signal: SIGINT
    depends_on:
      - postgres
    ports:
      - "${MICROSERVICE_PORT}:${MICROSERVICE_PORT}"
    volumes:
      - logs-volume:/app/logs/
    environment:
      MICROSERVICE_PORT: ${MICROSERVICE_PORT}
      MICROSERVICE_DSN: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
      MICROSERVICE_ER_API_KEY: ${MICROSERVICE_ER_API_KEY}
volumes:
  database-volume:
  logs-volume: